version: '3'

services:
  db:
    image: mariadb
    restart: always
    env_file: .env_mariadb
    volumes:
      - ./db_data:/var/lib/mysql

  wordpress1:
    depends_on:
      - db
    image: wordpress
    ports:
      - 8002:80
    restart: always
    env_file: .env_wordpress
    volumes:
      - ./wordpress:/var/www/html

  wordpress2:
    depends_on:
      - db
    image: wordpress
    ports:
      - 8001:80
    restart: always
    env_file: .env_wordpress
    volumes:
      - ./wordpress:/var/www/html

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  wordpress:

