version: '3.8'

services:
  tomcat:
    image: tomcat:11.0-jdk21-temurin
    deploy:
      replicas: 20
      resources:
        limits:
          memory: 1g

    networks:
      - reverse
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tomcat.rule=Host(`localhost`)"
      - "traefik.http.services.tomcat.loadbalancer.server.port=8080"

  nginx:
    image: nginx:latest
    container_name: nginx
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - reverse
    depends_on:
      - tomcat

  haproxy:
    image: haproxy:latest  # Usamos la última imagen de HAProxy
    container_name: haproxy
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - "82:80"  # Exponer el puerto 80 del contenedor en el puerto 80 del host
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg  # Montamos el archivo de configuración
    networks:
      - reverse
    depends_on:
      - tomcat
    ulimits:
      nofile:
        soft: 8192  # Límite suave de descriptores de archivos
        hard: 8192  # Límite duro de descriptores de archivos

  traefik:
    image: traefik:v2.5
    container_name: traefik
    deploy:
      resources:
        limits:
          memory: 1g
    command:
      - "--api.insecure=true"  # Habilita el panel de control (opcional)
      - "--providers.docker=true"  # Habilita el proveedor de Docker
      - "--entryPoints.web.address=:80"  # Escucha en el puerto 80
    ports:
      - "83:80"  # Puerto de entrada HTTP
    networks:
      - reverse
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Para que Traefik se integre con Docker

  envoy:
    image: envoyproxy/envoy:v1.20-latest
    container_name: envoy
    ports:
      - "84:80"
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml  # Monta la configuración de Envoy
    networks:
      - reverse

networks:
  reverse: #De reverse proxy xd
