version: '3.8'

services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    #ports:
    #  - "3000:80"
    networks:
      - nginx_net

networks:
  nginx_net:
    external: true
